### ISSUE TITLE
Edit repo website to point to: https://kopkins.github.io/Valhalla-Charts/

### ISSUE THREAD

**Issue by nvkelso** [Kopkins/Valhalla-Charts#10]
There's usually an edit button on the main page that allows the repo's website to be pasted in here (next to the repo description):

![screen shot 2016-06-09 at 15 25 47](https://cloud.githubusercontent.com/assets/853051/15948593/8b2898c4-2e56-11e6-98e7-edb4a8410e36.png)

**Comment by Kopkins** [comment]
Added Website
